# Site settings
title: "maxking's rants" # Your Title
tagline: 'Do or do not, there is no try. - Yoda'
sidebar_image: /images/debian.jpg

# Build settings
markdown: redcarpet
highlighter: pygments
#baseurl: / # the subpath of your site, e.g. /blog/
permalink: pretty
featured_image: /images/debian.jpb
